import type { Visit } from "@/types";

// Shown before someone logs their first visit. Shop references are seeded slugs (prisma/seed.ts).
export const exampleVisits: Visit[] = [
  {
    id: "example-kona",
    shopId: "kona-and-clay",
    date: "2026-10-01T09:30:00",
    stars: 5,
    duration: 2.5,
    amenities: ["wifi", "outlets", "quiet", "light"],
    orders: ["Pour-over", "Cardamom bun"],
    photos: [],
    example: true,
    note: "Incredible natural light by the front window bar. The Ethiopian natural single-origin was beautifully floral. My new morning writing spot.",
  },
  {
    id: "example-marrow",
    shopId: "marrow-coffee-works",
    date: "2026-09-28T14:00:00",
    stars: 4,
    duration: 3,
    amenities: ["wifi", "outlets", "tables"],
    orders: ["Cortado"],
    photos: [],
    example: true,
    note: "Great deep work session. Reliable high-speed internet, cozy walnut tables, and a perfect cortado. Headphones helped with the afternoon buzz.",
  },
  {
    id: "example-dune",
    shopId: "dune-roasters",
    date: "2026-09-24T10:00:00",
    stars: 5,
    duration: 1.5,
    amenities: ["light", "tables"],
    orders: ["Flat white", "Cardamom bun"],
    photos: [],
    example: true,
    note: "Delicious batch brew and a cardamom bun. The perfect Sunday reading nook. Stayed a little longer than planned.",
  },
  {
    id: "example-ninth",
    shopId: "ninth-street-espresso",
    date: "2026-09-12T08:00:00",
    stars: 4,
    duration: 0.5,
    amenities: ["light"],
    orders: ["Espresso"],
    photos: [],
    example: true,
    note: "No Wi-Fi, just coffee and neighborhood conversations. A quick standing-bar visit with a beautifully pulled double shot.",
  },
  {
    id: "example-linden",
    shopId: "linden-and-leaf",
    date: "2026-08-30T11:00:00",
    stars: 5,
    duration: 2,
    amenities: ["outdoor", "quiet"],
    orders: ["Matcha"],
    photos: [],
    example: true,
    note: "A hidden courtyard oasis. Soft wind chimes, a slow morning matcha, and sunlight through the leaves. Bring a notebook.",
  },
];
