'use client';

import { Button } from './ui/button';
import { LinkButton } from './ui/link-button';

import { useRef, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { amenityOptions, formatVisitDate, type Shop } from '@/lib/coffee-data';
import { useJournal } from './journal-provider';
import { Icon } from './icon';
import { BookmarkButton } from './shop-card';
import { NeighborhoodMap } from './neighborhood-map';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from './ui/dialog';

export function ShopDetail({ shop }: { shop: Shop }) {
  const { visits, notify } = useJournal();
  const logs = visits.filter(visit => visit.shopId === shop.id);
  const latest = [...logs].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())[0];
  const gallery = shop.id === 'kona-and-clay' ? ['/images/kona-interior.webp', '/images/pour-over.webp', '/images/window-seat.webp'] : [shop.image, shop.journalImage];
  const [photo, setPhoto] = useState(0);
  const [photosOpen, setPhotosOpen] = useState(false);
  const photosTrigger = useRef<HTMLElement>(null);
  async function share() {
    try {
      if (navigator.share) await navigator.share({ title: `${shop.name} · Cuptrail`, url: window.location.href });
      else { await navigator.clipboard.writeText(window.location.href); notify('Shop link copied.'); }
    } catch (error) { if (!(error instanceof DOMException && error.name === 'AbortError')) notify('The link could not be copied. You can share the address in your browser.'); }
  }
  return <Dialog open={photosOpen} onOpenChange={setPhotosOpen}><main id="main-content" className="page-width detail-main">
    <div className="detail-topbar"><Link href="/" className="back-link"><Icon name="back" size={16}/>Back to discover</Link><div className="detail-actions"><BookmarkButton shop={shop} showLabel/><Button variant="secondary" className="button button-soft" onClick={share}><Icon name="share" size={16}/><span>Share</span></Button><LinkButton variant="default" href={`/log-visit?shop=${shop.id}`} className="button button-accent hidden md:inline-flex"><Icon name="plus" size={17}/>Log a visit</LinkButton></div></div>
    <div className="detail-gallery">
      <Button variant="ghost" className="gallery-main h-[260px] sm:h-[300px] md:h-full p-0" aria-label={`View photos of ${shop.name}`} onClick={event => { photosTrigger.current = event.currentTarget; setPhoto(0); setPhotosOpen(true); }}><Image src={gallery[0]} alt={`Sunlit interior at ${shop.name}`} fill sizes="(max-width: 767px) 94vw, 65vw" preload className="object-cover"/><span className="gallery-category">{shop.category}</span><span className="gallery-photo-count"><Icon name="camera" size={15}/>{gallery.length} photos</span></Button>
      <div className="gallery-secondary">{gallery.slice(1).map((src, index) => <Button variant="ghost" className="h-full p-0" key={src} onClick={event => { photosTrigger.current = event.currentTarget; setPhoto(index + 1); setPhotosOpen(true); }} aria-label={`View ${index === 0 ? 'coffee' : 'window seat'} photo`}><Image src={src} alt={index === 0 ? `Coffee details at ${shop.name}` : `Window seating at ${shop.name}`} fill sizes="(max-width: 767px) 46vw, 30vw" className="object-cover"/>{shop.id === 'kona-and-clay' && <span>{index === 0 ? 'The pour-over ritual' : 'Your window seat'}</span>}</Button>)}</div>
    </div>
    <div className="detail-layout"><div className="detail-content">
      <section><div className="flex items-center gap-3 mb-3"><span className="roast-badge">{shop.roast}</span><span className="eyebrow text-muted-foreground">Sample shop</span></div><h1>{shop.name}</h1><p className="shop-address"><Icon name="pin" size={16}/>{shop.address}<span>·</span><span>{shop.distance} mi away</span></p></section>
      <div className="detail-metrics"><div><span className="eyebrow">Sample rating</span><strong>{shop.rating}<Icon name="star" size={15} fill/></strong><span>{shop.reviews} field notes</span></div><div><span className="eyebrow">Your rating</span><strong className="text-primary">{latest ? `${latest.stars}.0` : '—'}{latest && <Icon name="star" fill size={15}/>}</strong><span>{latest ? latest.example ? 'Example entry' : 'From your last visit' : 'Make it your own'}</span></div><div><span className="eyebrow">Wi-Fi</span><strong><Icon name="wifi" size={19}/>{shop.wifi ? `${shop.wifi} Mbps` : 'Unplugged'}</strong><span>{shop.wifi ? 'Sample speed' : 'Coffee & conversation'}</span></div><div><span className="eyebrow">Price range</span><strong>{'$'.repeat(shop.price)}</strong><span>{shop.price === 1 ? 'Everyday ritual' : 'A well-earned treat'}</span></div></div>
      <section className="detail-section"><p className="eyebrow text-primary mb-2">A place to pause</p><h2>Good coffee. A slower kind of day.</h2><p className="detail-description">{shop.description}</p></section>
      <section className="detail-section"><div className="section-heading"><h2>The feel of the place</h2><span className="eyebrow text-muted-foreground">From the design collection</span></div><div className="vibe-panel"><div><span><Icon name="volume" size={17}/>Atmosphere</span><strong>{shop.noise}</strong></div><div className="vibe-track"><span style={{ width: shop.amenities.includes('quiet') ? '32%' : '72%' }}/></div><div className="vibe-scale"><span>Quiet & calm</span><span>A lively little buzz</span></div><div className="mt-5"><span><Icon name="sun" size={17}/>Natural light</span><strong>{shop.amenities.includes('light') ? 'Sunlit corners' : 'Warm & intimate'}</strong></div><div className="vibe-track accent-track"><span style={{ width: shop.amenities.includes('light') ? '90%' : '50%' }}/></div><div className="vibe-scale"><span>A soft glow</span><span>Morning sunshine</span></div></div></section>
      <section className="detail-section"><div className="section-heading"><h2>Make yourself comfortable</h2><span className="eyebrow text-muted-foreground">Amenities</span></div><div className="detail-amenities">{amenityOptions.map(option => <div key={option.id} className={!shop.amenities.includes(option.id) ? 'unavailable-amenity' : ''}><Icon name={option.icon} size={21}/><div><strong>{option.label}</strong><span>{shop.amenities.includes(option.id) ? option.id === 'wifi' ? `${shop.wifi} Mbps in the sample design` : option.id === 'outlets' ? shop.outlets : 'Available in the sample design' : 'Not listed'}</span></div></div>)}</div></section>
      <section className="detail-section"><div className="section-heading"><h2>Your little field journal</h2><Link className="text-link" href={`/log-visit?shop=${shop.id}`}>Add a memory<Icon name="plus" size={14}/></Link></div>{logs.length ? <div className="detail-visits">{[...logs].sort((a,b) => new Date(b.date).getTime() - new Date(a.date).getTime()).map(visit => <article key={visit.id}><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="journal-avatar"><Icon name="book" size={17}/></span><div><h3>{visit.example ? 'A morning worth keeping' : 'Your coffee stop'}</h3><p>{formatVisitDate(visit.date, true)} · {visit.duration}h {visit.example && '· Example note'}</p></div></div><span className="rating"><Icon name="star" size={14} fill/>{visit.stars}.0</span></div><p className="detail-visit-note">{visit.note || 'A coffee stop worth remembering.'}</p><div className="amenity-tags">{visit.orders.map(order => <span key={order}>{order}</span>)}</div></article>)}</div> : <div className="detail-empty"><Icon name="book" size={26}/><p>No notes here just yet. Your first visit will be the start of something good.</p><Link href={`/log-visit?shop=${shop.id}`} className="text-link">Log your first visit<Icon name="arrow" size={14}/></Link></div>}</section>
    </div><aside className="detail-sidebar"><div className="detail-callout"><Icon name="coffee" size={26}/><h2>Been here already?</h2><p>Keep the little details. The coffee, the corner, and how it felt.</p><LinkButton variant="default" href={`/log-visit?shop=${shop.id}`} className="button button-accent"><Icon name="plus" size={16}/>Log your experience</LinkButton></div><section className="hours-card"><h2><Icon name="clock" size={17}/>Sample opening hours</h2><div><span>Monday – Friday</span><strong>{shop.hours}</strong></div><div><span>Saturday – Sunday</span><strong>8:00 AM – 6:00 PM</strong></div><p>Hours are part of the sample design. Check the actual venue before traveling.</p></section><section className="location-card"><div className="section-heading"><h2>In the neighborhood</h2><Icon name="pin" size={16}/></div><NeighborhoodMap shops={[shop]} compact/><p>{shop.neighborhood}, New York</p><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${shop.neighborhood}, New York`)}`} target="_blank" rel="noreferrer" className="text-link">Explore the area in Maps<Icon name="external" size={14}/></a></section></aside></div>
    <div className="mobile-detail-action"><LinkButton variant="default" href={`/log-visit?shop=${shop.id}`} className="button button-accent"><Icon name="plus" size={18}/>Log a visit</LinkButton></div>
    <DialogContent finalFocus={photosTrigger} className="photo-dialog sm:max-w-5xl block" showCloseButton={false}><DialogDescription className="sr-only">Browse sample shop photos with the previous and next buttons.</DialogDescription><div className="photo-dialog-top"><DialogTitle>{shop.name} · {photo + 1} / {gallery.length}</DialogTitle><Button variant="secondary" className="icon-button" onClick={() => setPhotosOpen(false)} aria-label="Close photos"><Icon name="close"/></Button></div><div className="photo-dialog-image"><Image src={gallery[photo]} alt={`${shop.name} photo ${photo + 1}`} fill sizes="90vw" className="object-contain"/></div><div className="flex justify-between pt-4"><Button variant="secondary" className="button button-soft" disabled={photo === 0} onClick={() => setPhoto(index => index - 1)}><Icon name="back" size={16}/>Previous</Button><Button variant="secondary" className="button button-soft" disabled={photo === gallery.length - 1} onClick={() => setPhoto(index => index + 1)}>Next<Icon name="arrow" size={16}/></Button></div></DialogContent>
  </main></Dialog>;
}
